# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Eatery.create(name: '취향', callnumber: '1', style: '1', openhour: '1', image: '1', menu: '1')
Eatery.create(name: '으리으리', callnumber: '1', style: '1', openhour: '1', image: '1', menu: '1')
Eatery.create(name: '논두렁', callnumber: '1', style: '1', openhour: '1', image: '1', menu: '1')
Eatery.create(name: '알촌', callnumber: '1', style: '1', openhour: '1', image: '1', menu: '1')
Eatery.create(name: '도스마스', callnumber: '1', style: '1', openhour: '1', image: '1', menu: '1')
Eatery.create(name: '', callnumber: '1', style: '1', openhour: '1', image: '1', menu: '1')
Eatery.create(name: '맥도날드', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '정성식당', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '지지고', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '더키친', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '추억과 김밥', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '황궁쟁반짜장', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '진국', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '뚝배기 파스타', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '백채 김치찌개', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '숭실골', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '대나무골', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '고기마을 찌개나라', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '찌개대학 부대과', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '멘동', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '우마이', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '빈털털이', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '손칼국수', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '아라 쭈꾸미', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '학생식당', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '교직원 식당', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '푸드코트', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '기숙사 식당', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '써브웨이', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '허그', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '스톤504', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '고기 스토리', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '미담길', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '코웍 비스트로', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '죠스떡볶이', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '현선이네', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '청년다방', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '할매 순대국', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '함박스테이크', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '왕돈까스 왕냉면', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '청운식당', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '가야성', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '연래춘', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '더피자', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '피자헤이븐', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '미주알 고주알', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '큰집갈비', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '간지 양꼬치', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '돈스앤덮밥', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '이레김밥', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '만복 국수', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '고추동', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '고인돌', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '엽기 떡볶이', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '신전 떡볶이', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '불타는 소금구이', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '풍년집', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '마포 갈매기', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '꼬레벵', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '이모네 족발, 보쌈', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '오니기리와 이규동', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '포36거리', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '설쌈냉면', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '송하', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '닭갈비 생각', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '봉구스 밥버거', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')


#술
Eatery.create(name: '상도 곱창', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '미쳐버린 파닭', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '상투골', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '파동추야', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '블루문', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '치킨매니아', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '봉구비어', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '비어구락부', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '올레', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '큐피드', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '디디치킨', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '주모리', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '젠', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '스팅', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '달달', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '개수작', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')
Eatery.create(name: '희망주립대', callnumber: ' ', style: '', openhour: ' ', image: ' ', menu: ' ')